#!/usr/bin/env python3
"""Losslessly re-encode existing CPR fonts, keeping rasterization and metrics.

Useful when a different host FreeType version would change regenerated glyphs.
Only generated font headers are accepted; each DEFLATE group and kerning matrix
is checked before an atomic replacement. This script never touches .cpfont files.
"""
import argparse
from pathlib import Path
from font_encoding import optimize_header


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory", type=Path)
    parser.add_argument("--zopfli", action="store_true")
    parser.add_argument("--write", action="store_true", help="Replace checked generated headers")
    args = parser.parse_args()
    total, count = 0, 0
    for path in sorted(args.directory.glob("*.h")):
        original = path.read_text(encoding="utf-8")
        if "generated by fontconvert.py" not in original:
            continue
        result, saved = optimize_header(original, args.zopfli)
        if result == original:
            continue
        if args.write:
            temporary = path.with_suffix(".h.encoding-tmp")
            try:
                temporary.write_text(result, encoding="utf-8", newline="\n")
                temporary.replace(path)
            finally:
                temporary.unlink(missing_ok=True)
        total += saved
        count += 1
        print(f"{path.name}: {saved:+d} flash bytes saved")
    print(f"{count} headers: {total} flash bytes saved (including new 32-bit pointers)")


if __name__ == "__main__":
    main()
