// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define BOOKERLY_10_FONT_ID (882858004)
#define BOOKERLY_12_FONT_ID (-493024735)
#define BOOKERLY_14_FONT_ID (46538448)
#define BOOKERLY_16_FONT_ID (1673670395)
#define BOOKERLY_18_FONT_ID (732232723)
#define NOTOSANS_10_FONT_ID (-1510226768)
#define NOTOSANS_12_FONT_ID (1597191560)
#define NOTOSANS_14_FONT_ID (-1413326613)
#define NOTOSANS_16_FONT_ID (116566294)
#define NOTOSANS_18_FONT_ID (-348426591)
#define UI_10_FONT_ID (1322569422)
#define UI_12_FONT_ID (1831230762)
#define SMALL_FONT_ID (1465627787)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(BOOKERLY_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BOOKERLY_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BOOKERLY_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BOOKERLY_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(BOOKERLY_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(NOTOSANS_18_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
